server:
  port: 8088
spring:
  application:
    name: E-learning
  datasource:
    url: jdbc:mysql://localhost:3306/elearning?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    dialect: org.hibernate.dialect.MySQL9Dialect
